apiVersion: v2
name: pagopa-ecommerce-cdc-service
description: Microservice that implements the change data capture on ecommerce events
type: application
version: 0.4.0
appVersion: 0.3.2
dependencies:
  - name: microservice-chart
    version: 7.5.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
